//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace etu_rehber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bolum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bolum()
        {
            this.liste = new HashSet<liste>();
        }
    
        public int bolum_id { get; set; }
        public string bolum_adi { get; set; }
        public int fak_id { get; set; }
    
        public virtual fakulte fakulte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<liste> liste { get; set; }
    }
}
