//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace etu_rehber.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class etu_rehberEntities : DbContext
    {
        public etu_rehberEntities()
            : base("name=etu_rehberEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<birim> birim { get; set; }
        public virtual DbSet<bolum> bolum { get; set; }
        public virtual DbSet<fakulte> fakulte { get; set; }
        public virtual DbSet<liste> liste { get; set; }
        public virtual DbSet<yetki> yetki { get; set; }
    }
}
